### PR TITLE
Refactored to work under GNOME 45

### LINKED ISSUE #20: Extension failed on GNOME Shell 45
**Describe the bug**
Screen Autorotate failed when enabling it on GNOME Shell 45

**To Reproduce**
1. Install either from both GNOME Extensions or Fedora repository
2. Switch the extension to ON

**Expected behavior**
Screen Autorotate should work as intended

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Fedora Linux 39 Design Suite
 - Browser: Firefox
 - Version: 12

**Additional context**
Generated trace back. See below

**Relevant logs (please use a tool like `fpaste` or a service like pastebin.)**
The settings of extension screen-rotate@shyzus.github.io had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
@file:///usr/share/gnome-shell/extensions/screen-rotate@shyzus.github.io/prefs.js:22:24
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

### PR DESCRIPTION
**Pull request by shyzus**
Closes #20 

This pull request makes this extension compatible with GNOME 45. Also dropping support for GNOME versions before GNOME 45.

Note: This extension has multiple tags that do still support GNOME 40 to GNOME 44. At the time of writing being [v13](https://github.com/shyzus/gnome-shell-extension-screen-autorotate/releases/tag/v13).

It is recommended to use https://extensions.gnome.org for downloading/installing this extension to avoid any issues regarding supported versions.

Thanks to @luyatshimbalanga for creating this issue and provide information and testing along with @yfreund for testing as well.

### CODE REVIEW

**Comment by yfreund** [comment]
Happy to help, @shyzus ! Quick note - you should decrease the version in `metadata.json` before publishing this.

**Comment by shyzus** [comment]
@yfreund Thanks for pointing it out. I believe https://extensions.gnome.org actually overwrites this value and generates its own version which if reviewed and accepted should be the version 14. If it doesn't then il update it manually.

**Comment by yfreund** [comment]
@shyzus I have yet to publish any extensions myself, so I'm not sure if this is the case or not, but AFAIK if the value would end up being set to 99 on the version uploaded to the gnome extensions page, newer versions with lower numbers will not be pulled by the clients.
I strongly suggest doing the manual fix first, just to be on the safe side.

**Comment by shyzus** [comment]
@yfreund I just looked trough the history of the metadata.json file. It has had its version value wrong for different releases especially when it was just forked from the kosmospredanie repo. The versions presented on extensions.gnome.org however have always been incremental and in-order.  I think it is certain to say that extensions.gnome.org does overwrite the value.

I will manually update the version value in the repo since downloading from EGO will have the right version but anyone that directly fetches from github will have 99 as the version.

I have already submitted the existing pre-release v14 to EGO. but considering a resubmission would be wasting reviewer time for a one line change to a version number. il update it in the repo and retag it to contain the right version number.

**Pull request merged**
